To Do list: add & remove
cilfonegabriel/ToDoList pull request #2
Opened 2022-12-15 19:08 UTC by cilfonegabriel

In this project, CRUD (create, read, update, delete) methods were implemented. All user interface elements are fully functional and your application will be complete.
- Removed all coded items from the task matrix.
- A new JavaScript file was created for the new functionality.
- Implemented a function to add a new task (add a new element to the array).
- Implemented a function to delete a task (remove an element from the array).
- Added a feature to edit task descriptions.
- Deleting a task updates the indices of all remaining items,
- All changes to the task list have been saved to local storage.

2022-12-15 20:15 UTC, Felix45 requested changes
Hi @cilfonegabriel , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights :heavy_check_mark: 
- [ ] :heavy_check_mark: Descriptive pull request title and summary
- [ ] :heavy_check_mark: GitHub flow is correctly used
- [ ] :heavy_check_mark: Good descriptive commit messages
- [ ] :heavy_check_mark: All linter checks are setup and passing 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 20:15 UTC, Felix45 commented on src/index.js
> +});
- [ Required] :+1:  Good job implementing the `addTodo` to the todo list it works well and updates the local storage, however when I try to delete a todo from the todo list it is removed from the list but the local storage is not updated. This means when I refresh the page the `todo` item is still there, please consider updating the local storage so that when the webpage is reloaded it contains only the todos that were not deleted. Please see the video below for more details on this.

https://user-images.githubusercontent.com/16392046/207953698-1b0984b2-e61c-4da5-a345-9b1de32f9daf.mp4

2022-12-15 20:15 UTC, Felix45 commented on src/modules/taskEvents.js
> +    <input class="task-description" value="${desc}">
- [ Required] Please consider adding an `event listener` that allows a user to edit the description of a `todo` item on the to-do list. When I tried to update a `todo` the change did not reflect in the local storage. You can achieve this by registering an `onchange` event listener on the `.task-description` input elements, then when a task description changes remember to update the local storage. Please see the video below for more details on this.

## Project requirement
![Screenshot from 2022-12-15 22-58-25](https://user-images.githubusercontent.com/16392046/207956828-dec78360-2ed2-4c46-885c-3c9fc86a04e2.png)

https://user-images.githubusercontent.com/16392046/207956513-a656de89-24fc-481a-ab3c-a85603407e99.mp4

2022-12-17 11:24 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @cilfonegabriel 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-17 11:26 UTC, merged